//= require 'vendor/jquery'
//= require 'vendor/underscore'
//= require 'fttojson'

//= require 'plugins'
//= require 'map_ccd'
//= require 'gm_icons'
//= require 'mapper'
//= require 'geo_localizator'
//= require 'fusion_proxy'
//= require 'geo_driver'
//= require 'filter'
//= require 'filter_reset'
//= require 'ccd'
//= require 'app'
